#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ReceitaPedia")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertingredientes(ingredientes instance);
  partial void Updateingredientes(ingredientes instance);
  partial void Deleteingredientes(ingredientes instance);
  partial void InsertingredientesReceitas(ingredientesReceitas instance);
  partial void UpdateingredientesReceitas(ingredientesReceitas instance);
  partial void DeleteingredientesReceitas(ingredientesReceitas instance);
  partial void Insertpessoa(pessoa instance);
  partial void Updatepessoa(pessoa instance);
  partial void Deletepessoa(pessoa instance);
  partial void Insertreceitas(receitas instance);
  partial void Updatereceitas(receitas instance);
  partial void Deletereceitas(receitas instance);
  partial void InserttipoReceitas(tipoReceitas instance);
  partial void UpdatetipoReceitas(tipoReceitas instance);
  partial void DeletetipoReceitas(tipoReceitas instance);
  partial void InsertunidadesMedidas(unidadesMedidas instance);
  partial void UpdateunidadesMedidas(unidadesMedidas instance);
  partial void DeleteunidadesMedidas(unidadesMedidas instance);
  partial void Insertavaliacao(avaliacao instance);
  partial void Updateavaliacao(avaliacao instance);
  partial void Deleteavaliacao(avaliacao instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ReceitaPediaConnectionString1"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<ingredientes> ingredientes
	{
		get
		{
			return this.GetTable<ingredientes>();
		}
	}
	
	public System.Data.Linq.Table<ingredientesReceitas> ingredientesReceitas
	{
		get
		{
			return this.GetTable<ingredientesReceitas>();
		}
	}
	
	public System.Data.Linq.Table<pessoa> pessoa
	{
		get
		{
			return this.GetTable<pessoa>();
		}
	}
	
	public System.Data.Linq.Table<receitas> receitas
	{
		get
		{
			return this.GetTable<receitas>();
		}
	}
	
	public System.Data.Linq.Table<tipoReceitas> tipoReceitas
	{
		get
		{
			return this.GetTable<tipoReceitas>();
		}
	}
	
	public System.Data.Linq.Table<unidadesMedidas> unidadesMedidas
	{
		get
		{
			return this.GetTable<unidadesMedidas>();
		}
	}
	
	public System.Data.Linq.Table<avaliacao> avaliacao
	{
		get
		{
			return this.GetTable<avaliacao>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ingredientes")]
public partial class ingredientes : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _ingrediente;
	
	private EntitySet<ingredientesReceitas> _ingredientesReceitas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OningredienteChanging(string value);
    partial void OningredienteChanged();
    #endregion
	
	public ingredientes()
	{
		this._ingredientesReceitas = new EntitySet<ingredientesReceitas>(new Action<ingredientesReceitas>(this.attach_ingredientesReceitas), new Action<ingredientesReceitas>(this.detach_ingredientesReceitas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ingrediente", DbType="VarChar(100)")]
	public string ingrediente
	{
		get
		{
			return this._ingrediente;
		}
		set
		{
			if ((this._ingrediente != value))
			{
				this.OningredienteChanging(value);
				this.SendPropertyChanging();
				this._ingrediente = value;
				this.SendPropertyChanged("ingrediente");
				this.OningredienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ingredientes_ingredientesReceitas", Storage="_ingredientesReceitas", ThisKey="id", OtherKey="id_ingrediente")]
	public EntitySet<ingredientesReceitas> ingredientesReceitas
	{
		get
		{
			return this._ingredientesReceitas;
		}
		set
		{
			this._ingredientesReceitas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ingredientesReceitas(ingredientesReceitas entity)
	{
		this.SendPropertyChanging();
		entity.ingredientes = this;
	}
	
	private void detach_ingredientesReceitas(ingredientesReceitas entity)
	{
		this.SendPropertyChanging();
		entity.ingredientes = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ingredientesReceitas")]
public partial class ingredientesReceitas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_receita;
	
	private int _id_ingrediente;
	
	private int _qtd;
	
	private int _id_unidade;
	
	private EntityRef<ingredientes> _ingredientes;
	
	private EntityRef<receitas> _receitas;
	
	private EntityRef<unidadesMedidas> _unidadesMedidas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_receitaChanging(int value);
    partial void Onid_receitaChanged();
    partial void Onid_ingredienteChanging(int value);
    partial void Onid_ingredienteChanged();
    partial void OnqtdChanging(int value);
    partial void OnqtdChanged();
    partial void Onid_unidadeChanging(int value);
    partial void Onid_unidadeChanged();
    #endregion
	
	public ingredientesReceitas()
	{
		this._ingredientes = default(EntityRef<ingredientes>);
		this._receitas = default(EntityRef<receitas>);
		this._unidadesMedidas = default(EntityRef<unidadesMedidas>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_receita", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id_receita
	{
		get
		{
			return this._id_receita;
		}
		set
		{
			if ((this._id_receita != value))
			{
				if (this._receitas.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_receitaChanging(value);
				this.SendPropertyChanging();
				this._id_receita = value;
				this.SendPropertyChanged("id_receita");
				this.Onid_receitaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_ingrediente", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int id_ingrediente
	{
		get
		{
			return this._id_ingrediente;
		}
		set
		{
			if ((this._id_ingrediente != value))
			{
				if (this._ingredientes.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_ingredienteChanging(value);
				this.SendPropertyChanging();
				this._id_ingrediente = value;
				this.SendPropertyChanged("id_ingrediente");
				this.Onid_ingredienteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qtd", DbType="Int NOT NULL")]
	public int qtd
	{
		get
		{
			return this._qtd;
		}
		set
		{
			if ((this._qtd != value))
			{
				this.OnqtdChanging(value);
				this.SendPropertyChanging();
				this._qtd = value;
				this.SendPropertyChanged("qtd");
				this.OnqtdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_unidade", DbType="Int NOT NULL")]
	public int id_unidade
	{
		get
		{
			return this._id_unidade;
		}
		set
		{
			if ((this._id_unidade != value))
			{
				if (this._unidadesMedidas.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_unidadeChanging(value);
				this.SendPropertyChanging();
				this._id_unidade = value;
				this.SendPropertyChanged("id_unidade");
				this.Onid_unidadeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ingredientes_ingredientesReceitas", Storage="_ingredientes", ThisKey="id_ingrediente", OtherKey="id", IsForeignKey=true)]
	public ingredientes ingredientes
	{
		get
		{
			return this._ingredientes.Entity;
		}
		set
		{
			ingredientes previousValue = this._ingredientes.Entity;
			if (((previousValue != value) 
						|| (this._ingredientes.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._ingredientes.Entity = null;
					previousValue.ingredientesReceitas.Remove(this);
				}
				this._ingredientes.Entity = value;
				if ((value != null))
				{
					value.ingredientesReceitas.Add(this);
					this._id_ingrediente = value.id;
				}
				else
				{
					this._id_ingrediente = default(int);
				}
				this.SendPropertyChanged("ingredientes");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receitas_ingredientesReceitas", Storage="_receitas", ThisKey="id_receita", OtherKey="id", IsForeignKey=true)]
	public receitas receitas
	{
		get
		{
			return this._receitas.Entity;
		}
		set
		{
			receitas previousValue = this._receitas.Entity;
			if (((previousValue != value) 
						|| (this._receitas.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._receitas.Entity = null;
					previousValue.ingredientesReceitas.Remove(this);
				}
				this._receitas.Entity = value;
				if ((value != null))
				{
					value.ingredientesReceitas.Add(this);
					this._id_receita = value.id;
				}
				else
				{
					this._id_receita = default(int);
				}
				this.SendPropertyChanged("receitas");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidadesMedidas_ingredientesReceitas", Storage="_unidadesMedidas", ThisKey="id_unidade", OtherKey="id_unidade", IsForeignKey=true)]
	public unidadesMedidas unidadesMedidas
	{
		get
		{
			return this._unidadesMedidas.Entity;
		}
		set
		{
			unidadesMedidas previousValue = this._unidadesMedidas.Entity;
			if (((previousValue != value) 
						|| (this._unidadesMedidas.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._unidadesMedidas.Entity = null;
					previousValue.ingredientesReceitas.Remove(this);
				}
				this._unidadesMedidas.Entity = value;
				if ((value != null))
				{
					value.ingredientesReceitas.Add(this);
					this._id_unidade = value.id_unidade;
				}
				else
				{
					this._id_unidade = default(int);
				}
				this.SendPropertyChanged("unidadesMedidas");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.pessoa")]
public partial class pessoa : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _nome;
	
	private string _cpf;
	
	private string _email;
	
	private string _senha;
	
	private System.Nullable<int> _nivel;
	
	private EntitySet<receitas> _receitas;
	
	private EntitySet<avaliacao> _avaliacao;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnomeChanging(string value);
    partial void OnnomeChanged();
    partial void OncpfChanging(string value);
    partial void OncpfChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnsenhaChanging(string value);
    partial void OnsenhaChanged();
    partial void OnnivelChanging(System.Nullable<int> value);
    partial void OnnivelChanged();
    #endregion
	
	public pessoa()
	{
		this._receitas = new EntitySet<receitas>(new Action<receitas>(this.attach_receitas), new Action<receitas>(this.detach_receitas));
		this._avaliacao = new EntitySet<avaliacao>(new Action<avaliacao>(this.attach_avaliacao), new Action<avaliacao>(this.detach_avaliacao));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nome", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string nome
	{
		get
		{
			return this._nome;
		}
		set
		{
			if ((this._nome != value))
			{
				this.OnnomeChanging(value);
				this.SendPropertyChanging();
				this._nome = value;
				this.SendPropertyChanged("nome");
				this.OnnomeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cpf", DbType="VarChar(40) NOT NULL", CanBeNull=false)]
	public string cpf
	{
		get
		{
			return this._cpf;
		}
		set
		{
			if ((this._cpf != value))
			{
				this.OncpfChanging(value);
				this.SendPropertyChanging();
				this._cpf = value;
				this.SendPropertyChanged("cpf");
				this.OncpfChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_senha", DbType="VarChar(8) NOT NULL", CanBeNull=false)]
	public string senha
	{
		get
		{
			return this._senha;
		}
		set
		{
			if ((this._senha != value))
			{
				this.OnsenhaChanging(value);
				this.SendPropertyChanging();
				this._senha = value;
				this.SendPropertyChanged("senha");
				this.OnsenhaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nivel", DbType="Int")]
	public System.Nullable<int> nivel
	{
		get
		{
			return this._nivel;
		}
		set
		{
			if ((this._nivel != value))
			{
				this.OnnivelChanging(value);
				this.SendPropertyChanging();
				this._nivel = value;
				this.SendPropertyChanged("nivel");
				this.OnnivelChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pessoa_receitas", Storage="_receitas", ThisKey="id", OtherKey="pessoa")]
	public EntitySet<receitas> receitas
	{
		get
		{
			return this._receitas;
		}
		set
		{
			this._receitas.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pessoa_avaliacao", Storage="_avaliacao", ThisKey="id", OtherKey="id_pessoa")]
	public EntitySet<avaliacao> avaliacao
	{
		get
		{
			return this._avaliacao;
		}
		set
		{
			this._avaliacao.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_receitas(receitas entity)
	{
		this.SendPropertyChanging();
		entity.pessoa1 = this;
	}
	
	private void detach_receitas(receitas entity)
	{
		this.SendPropertyChanging();
		entity.pessoa1 = null;
	}
	
	private void attach_avaliacao(avaliacao entity)
	{
		this.SendPropertyChanging();
		entity.pessoa = this;
	}
	
	private void detach_avaliacao(avaliacao entity)
	{
		this.SendPropertyChanging();
		entity.pessoa = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.receitas")]
public partial class receitas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _receita;
	
	private int _pessoa;
	
	private int _tipo_receita;
	
	private string _preparo;
	
	private System.DateTime _data_postagem;
	
	private EntitySet<ingredientesReceitas> _ingredientesReceitas;
	
	private EntitySet<avaliacao> _avaliacao;
	
	private EntityRef<pessoa> _pessoa1;
	
	private EntityRef<tipoReceitas> _tipoReceitas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnreceitaChanging(string value);
    partial void OnreceitaChanged();
    partial void OnpessoaChanging(int value);
    partial void OnpessoaChanged();
    partial void Ontipo_receitaChanging(int value);
    partial void Ontipo_receitaChanged();
    partial void OnpreparoChanging(string value);
    partial void OnpreparoChanged();
    partial void Ondata_postagemChanging(System.DateTime value);
    partial void Ondata_postagemChanged();
    #endregion
	
	public receitas()
	{
		this._ingredientesReceitas = new EntitySet<ingredientesReceitas>(new Action<ingredientesReceitas>(this.attach_ingredientesReceitas), new Action<ingredientesReceitas>(this.detach_ingredientesReceitas));
		this._avaliacao = new EntitySet<avaliacao>(new Action<avaliacao>(this.attach_avaliacao), new Action<avaliacao>(this.detach_avaliacao));
		this._pessoa1 = default(EntityRef<pessoa>);
		this._tipoReceitas = default(EntityRef<tipoReceitas>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_receita", DbType="VarChar(40)")]
	public string receita
	{
		get
		{
			return this._receita;
		}
		set
		{
			if ((this._receita != value))
			{
				this.OnreceitaChanging(value);
				this.SendPropertyChanging();
				this._receita = value;
				this.SendPropertyChanged("receita");
				this.OnreceitaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pessoa", DbType="Int NOT NULL")]
	public int pessoa
	{
		get
		{
			return this._pessoa;
		}
		set
		{
			if ((this._pessoa != value))
			{
				if (this._pessoa1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnpessoaChanging(value);
				this.SendPropertyChanging();
				this._pessoa = value;
				this.SendPropertyChanged("pessoa");
				this.OnpessoaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipo_receita", DbType="Int NOT NULL")]
	public int tipo_receita
	{
		get
		{
			return this._tipo_receita;
		}
		set
		{
			if ((this._tipo_receita != value))
			{
				if (this._tipoReceitas.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ontipo_receitaChanging(value);
				this.SendPropertyChanging();
				this._tipo_receita = value;
				this.SendPropertyChanged("tipo_receita");
				this.Ontipo_receitaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_preparo", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
	public string preparo
	{
		get
		{
			return this._preparo;
		}
		set
		{
			if ((this._preparo != value))
			{
				this.OnpreparoChanging(value);
				this.SendPropertyChanging();
				this._preparo = value;
				this.SendPropertyChanged("preparo");
				this.OnpreparoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_data_postagem", DbType="Date NOT NULL")]
	public System.DateTime data_postagem
	{
		get
		{
			return this._data_postagem;
		}
		set
		{
			if ((this._data_postagem != value))
			{
				this.Ondata_postagemChanging(value);
				this.SendPropertyChanging();
				this._data_postagem = value;
				this.SendPropertyChanged("data_postagem");
				this.Ondata_postagemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receitas_ingredientesReceitas", Storage="_ingredientesReceitas", ThisKey="id", OtherKey="id_receita")]
	public EntitySet<ingredientesReceitas> ingredientesReceitas
	{
		get
		{
			return this._ingredientesReceitas;
		}
		set
		{
			this._ingredientesReceitas.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receitas_avaliacao", Storage="_avaliacao", ThisKey="id", OtherKey="id_receita")]
	public EntitySet<avaliacao> avaliacao
	{
		get
		{
			return this._avaliacao;
		}
		set
		{
			this._avaliacao.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pessoa_receitas", Storage="_pessoa1", ThisKey="pessoa", OtherKey="id", IsForeignKey=true)]
	public pessoa pessoa1
	{
		get
		{
			return this._pessoa1.Entity;
		}
		set
		{
			pessoa previousValue = this._pessoa1.Entity;
			if (((previousValue != value) 
						|| (this._pessoa1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._pessoa1.Entity = null;
					previousValue.receitas.Remove(this);
				}
				this._pessoa1.Entity = value;
				if ((value != null))
				{
					value.receitas.Add(this);
					this._pessoa = value.id;
				}
				else
				{
					this._pessoa = default(int);
				}
				this.SendPropertyChanged("pessoa1");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoReceitas_receitas", Storage="_tipoReceitas", ThisKey="tipo_receita", OtherKey="id", IsForeignKey=true)]
	public tipoReceitas tipoReceitas
	{
		get
		{
			return this._tipoReceitas.Entity;
		}
		set
		{
			tipoReceitas previousValue = this._tipoReceitas.Entity;
			if (((previousValue != value) 
						|| (this._tipoReceitas.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._tipoReceitas.Entity = null;
					previousValue.receitas.Remove(this);
				}
				this._tipoReceitas.Entity = value;
				if ((value != null))
				{
					value.receitas.Add(this);
					this._tipo_receita = value.id;
				}
				else
				{
					this._tipo_receita = default(int);
				}
				this.SendPropertyChanged("tipoReceitas");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ingredientesReceitas(ingredientesReceitas entity)
	{
		this.SendPropertyChanging();
		entity.receitas = this;
	}
	
	private void detach_ingredientesReceitas(ingredientesReceitas entity)
	{
		this.SendPropertyChanging();
		entity.receitas = null;
	}
	
	private void attach_avaliacao(avaliacao entity)
	{
		this.SendPropertyChanging();
		entity.receitas = this;
	}
	
	private void detach_avaliacao(avaliacao entity)
	{
		this.SendPropertyChanging();
		entity.receitas = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tipoReceitas")]
public partial class tipoReceitas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private string _tipoReceita;
	
	private EntitySet<receitas> _receitas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OntipoReceitaChanging(string value);
    partial void OntipoReceitaChanged();
    #endregion
	
	public tipoReceitas()
	{
		this._receitas = new EntitySet<receitas>(new Action<receitas>(this.attach_receitas), new Action<receitas>(this.detach_receitas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tipoReceita", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
	public string tipoReceita
	{
		get
		{
			return this._tipoReceita;
		}
		set
		{
			if ((this._tipoReceita != value))
			{
				this.OntipoReceitaChanging(value);
				this.SendPropertyChanging();
				this._tipoReceita = value;
				this.SendPropertyChanged("tipoReceita");
				this.OntipoReceitaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tipoReceitas_receitas", Storage="_receitas", ThisKey="id", OtherKey="tipo_receita")]
	public EntitySet<receitas> receitas
	{
		get
		{
			return this._receitas;
		}
		set
		{
			this._receitas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_receitas(receitas entity)
	{
		this.SendPropertyChanging();
		entity.tipoReceitas = this;
	}
	
	private void detach_receitas(receitas entity)
	{
		this.SendPropertyChanging();
		entity.tipoReceitas = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.unidadesMedidas")]
public partial class unidadesMedidas : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id_unidade;
	
	private string _unidade;
	
	private EntitySet<ingredientesReceitas> _ingredientesReceitas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_unidadeChanging(int value);
    partial void Onid_unidadeChanged();
    partial void OnunidadeChanging(string value);
    partial void OnunidadeChanged();
    #endregion
	
	public unidadesMedidas()
	{
		this._ingredientesReceitas = new EntitySet<ingredientesReceitas>(new Action<ingredientesReceitas>(this.attach_ingredientesReceitas), new Action<ingredientesReceitas>(this.detach_ingredientesReceitas));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_unidade", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id_unidade
	{
		get
		{
			return this._id_unidade;
		}
		set
		{
			if ((this._id_unidade != value))
			{
				this.Onid_unidadeChanging(value);
				this.SendPropertyChanging();
				this._id_unidade = value;
				this.SendPropertyChanged("id_unidade");
				this.Onid_unidadeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unidade", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string unidade
	{
		get
		{
			return this._unidade;
		}
		set
		{
			if ((this._unidade != value))
			{
				this.OnunidadeChanging(value);
				this.SendPropertyChanging();
				this._unidade = value;
				this.SendPropertyChanged("unidade");
				this.OnunidadeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="unidadesMedidas_ingredientesReceitas", Storage="_ingredientesReceitas", ThisKey="id_unidade", OtherKey="id_unidade")]
	public EntitySet<ingredientesReceitas> ingredientesReceitas
	{
		get
		{
			return this._ingredientesReceitas;
		}
		set
		{
			this._ingredientesReceitas.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ingredientesReceitas(ingredientesReceitas entity)
	{
		this.SendPropertyChanging();
		entity.unidadesMedidas = this;
	}
	
	private void detach_ingredientesReceitas(ingredientesReceitas entity)
	{
		this.SendPropertyChanging();
		entity.unidadesMedidas = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.avaliacao")]
public partial class avaliacao : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _id;
	
	private int _id_receita;
	
	private int _id_pessoa;
	
	private int _nota;
	
	private EntityRef<pessoa> _pessoa;
	
	private EntityRef<receitas> _receitas;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void Onid_receitaChanging(int value);
    partial void Onid_receitaChanged();
    partial void Onid_pessoaChanging(int value);
    partial void Onid_pessoaChanged();
    partial void OnnotaChanging(int value);
    partial void OnnotaChanged();
    #endregion
	
	public avaliacao()
	{
		this._pessoa = default(EntityRef<pessoa>);
		this._receitas = default(EntityRef<receitas>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int id
	{
		get
		{
			return this._id;
		}
		set
		{
			if ((this._id != value))
			{
				this.OnidChanging(value);
				this.SendPropertyChanging();
				this._id = value;
				this.SendPropertyChanged("id");
				this.OnidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_receita", DbType="Int NOT NULL")]
	public int id_receita
	{
		get
		{
			return this._id_receita;
		}
		set
		{
			if ((this._id_receita != value))
			{
				if (this._receitas.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_receitaChanging(value);
				this.SendPropertyChanging();
				this._id_receita = value;
				this.SendPropertyChanged("id_receita");
				this.Onid_receitaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_pessoa", DbType="Int NOT NULL")]
	public int id_pessoa
	{
		get
		{
			return this._id_pessoa;
		}
		set
		{
			if ((this._id_pessoa != value))
			{
				if (this._pessoa.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onid_pessoaChanging(value);
				this.SendPropertyChanging();
				this._id_pessoa = value;
				this.SendPropertyChanged("id_pessoa");
				this.Onid_pessoaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nota", DbType="Int NOT NULL")]
	public int nota
	{
		get
		{
			return this._nota;
		}
		set
		{
			if ((this._nota != value))
			{
				this.OnnotaChanging(value);
				this.SendPropertyChanging();
				this._nota = value;
				this.SendPropertyChanged("nota");
				this.OnnotaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="pessoa_avaliacao", Storage="_pessoa", ThisKey="id_pessoa", OtherKey="id", IsForeignKey=true)]
	public pessoa pessoa
	{
		get
		{
			return this._pessoa.Entity;
		}
		set
		{
			pessoa previousValue = this._pessoa.Entity;
			if (((previousValue != value) 
						|| (this._pessoa.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._pessoa.Entity = null;
					previousValue.avaliacao.Remove(this);
				}
				this._pessoa.Entity = value;
				if ((value != null))
				{
					value.avaliacao.Add(this);
					this._id_pessoa = value.id;
				}
				else
				{
					this._id_pessoa = default(int);
				}
				this.SendPropertyChanged("pessoa");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="receitas_avaliacao", Storage="_receitas", ThisKey="id_receita", OtherKey="id", IsForeignKey=true)]
	public receitas receitas
	{
		get
		{
			return this._receitas.Entity;
		}
		set
		{
			receitas previousValue = this._receitas.Entity;
			if (((previousValue != value) 
						|| (this._receitas.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._receitas.Entity = null;
					previousValue.avaliacao.Remove(this);
				}
				this._receitas.Entity = value;
				if ((value != null))
				{
					value.avaliacao.Add(this);
					this._id_receita = value.id;
				}
				else
				{
					this._id_receita = default(int);
				}
				this.SendPropertyChanged("receitas");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
